# Generated by Django 4.2.11 on 2024-04-01 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("exchange", models.CharField(max_length=100, verbose_name="交易所名称")),
                ("api_key", models.CharField(max_length=200, verbose_name="Api Key")),
                (
                    "api_secret",
                    models.CharField(max_length=200, verbose_name="Api Secret"),
                ),
                (
                    "passphrase",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Api passphrase",
                    ),
                ),
                (
                    "taker_fee_rate",
                    models.DecimalField(decimal_places=4, max_digits=5, verbose_name="Taker费率"),
                ),
                (
                    "maker_fee_rate",
                    models.DecimalField(decimal_places=4, max_digits=5, verbose_name="Maker费率"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "账户",
                "verbose_name_plural": "账户",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, verbose_name="Order ID")),
                (
                    "client_order_id",
                    models.CharField(max_length=100, verbose_name="Client Order ID"),
                ),
                (
                    "instrument_name",
                    models.CharField(max_length=100, verbose_name="交易对"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="价格"),
                ),
                (
                    "filled_price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="成交价格"),
                ),
                (
                    "size",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="数量"),
                ),
                (
                    "filled_size",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="成交数量"),
                ),
                (
                    "fee",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="手续费"),
                ),
                ("fee_currency", models.CharField(max_length=20, verbose_name="手续费币种")),
                ("created_at", models.DateTimeField(verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("manager", models.CharField(max_length=100, verbose_name="管理人")),
                (
                    "min_open_rate",
                    models.DecimalField(decimal_places=4, max_digits=5, verbose_name="开仓最低收益率"),
                ),
                (
                    "max_close_rate",
                    models.DecimalField(decimal_places=4, max_digits=5, verbose_name="平仓最高收益率"),
                ),
                (
                    "per_order_usd",
                    models.PositiveIntegerField(help_text="100的整数倍，每笔订单按照该数据进行下单", verbose_name="单笔订单金额(USD)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "max_position_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="可选。策略持仓占市场当前持仓的最大比例，超过该比例不进行开仓",
                        max_digits=5,
                        null=True,
                        verbose_name="持仓最大占比",
                    ),
                ),
                (
                    "max_position_value",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="可选。限制单个币种的最大持仓量USD市值",
                        null=True,
                        verbose_name="最大持仓市值",
                    ),
                ),
                (
                    "accounts",
                    models.ManyToManyField(to="strategy.account", verbose_name="关联账户"),
                ),
            ],
            options={
                "verbose_name": "策略",
                "verbose_name_plural": "策略",
            },
        ),
        migrations.CreateModel(
            name="NetValueSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "net_value",
                    models.DecimalField(decimal_places=4, max_digits=10, verbose_name="净值"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.account",
                        verbose_name="关联账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "净值快照",
                "verbose_name_plural": "净值快照",
            },
        ),
    ]
