# Generated by Django 4.2.11 on 2024-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="passphrase",
            new_name="api_passphrase",
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="名称"),
        ),
    ]
