# Generated by Django 4.2.11 on 2024-04-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0004_alter_strategy_max_close_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.IntegerField(
                choices=[
                    (100, "初始化"),
                    (101, "已下单"),
                    (103, "已成交"),
                    (102, "已部分成交"),
                    (104, "已取消"),
                    (105, "已部分取消"),
                    (106, "取消中"),
                    (-1, "下单失败"),
                    (-2, "下单异常"),
                ],
                default=100,
                verbose_name="状态",
            ),
        ),
    ]
