# Generated by Django 4.2.11 on 2024-04-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0005_order_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "net_value",
                    models.DecimalField(decimal_places=4, max_digits=10, verbose_name="净值"),
                ),
                ("raw_data", models.JSONField(verbose_name="原始数据")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.account",
                        verbose_name="关联账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "净值快照",
                "verbose_name_plural": "净值快照",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="raw_data",
            field=models.JSONField(default="", verbose_name="原始数据"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="NetValueSnapshot",
        ),
    ]
