# Generated by Django 4.2.11 on 2024-04-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0006_equitysnapshot_order_raw_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="side",
            field=models.IntegerField(choices=[[1, "BUY"], [-1, "SELL"]], default=None, verbose_name="方向"),
            preserve_default=False,
        ),
    ]
