# Generated by Django 4.2.11 on 2024-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0007_order_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="black_list",
            field=models.JSONField(blank=True, help_text="可选。不进行交易的币种", null=True, verbose_name="币种黑名单"),
        ),
    ]
